### ISSUE TITLE
Fix Crash for User Api

### ISSUE THREAD

**Issue by aggarwalpulkit596** [coding-blocks/Chatter#130] opened 2018-07-28 04:52 UTC
Crash on Calling User Api
![screenshot 2018-07-28 at 10 19 09 am](https://user-images.githubusercontent.com/29139786/43353213-1e21fcba-9250-11e8-80eb-a526ef3f9dd9.png)

**Comment by abishekvashok** [comment] 2018-08-02 08:06
Duplicate of #39 Fixed in #142 : Claimed a bounty of 100

**Closed** 2018-08-12 13:43 UTC
Labels: BOSS, BOUNTY: 200
